export const ACTIVATE_API_KEY = "ACTIVATE_API_KEY";
export const ACTIVATE_API_KEY_SUCCESS = "ACTIVATE_API_KEY_SUCCESS";
export const ACTIVATE_API_KEY_FAILURE = "ACTIVATE_API_KEY_FAILURE";

export const REMOVE_API_KEY = "REMOVE_API_KEY";
